# Generated by Django 5.2.2 on 2025-06-14 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name_plural': 'Категории трат',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='expense_exp_name_f951bb_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.expensecategory')),
            ],
            options={
                'verbose_name': 'Траты',
                'verbose_name_plural': 'Траты',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['id'], name='expense_exp_id_1a6bd4_idx'), models.Index(fields=['-date'], name='expense_exp_date_5e5d86_idx')],
            },
        ),
    ]
