# Generated by Django 5.2.2 on 2025-06-24 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expense', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['name'], name='expense_exp_name_f951bb_idx'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='expense.expensecategory'),
        ),
        migrations.AddField(
            model_name='expensecategorylimit',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='expense.expensecategory'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['id'], name='expense_exp_id_1a6bd4_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['-date'], name='expense_exp_date_5e5d86_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategorylimit',
            unique_together={('category', 'month')},
        ),
    ]
