# Generated by Django 5.2.2 on 2025-06-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expensecategory',
            name='slug',
        ),
    ]
