# Generated by Django 5.2.2 on 2025-06-19 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_remove_expensecategory_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategoryLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('limit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limits', to='expense.expensecategory')),
            ],
            options={
                'unique_together': {('category', 'month')},
            },
        ),
    ]
